spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tutordesk}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.port=40232
server.forward-headers-strategy=native
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.internal-proxies=.*

app.admin.username=${APP_ADMIN_USERNAME}
app.admin.password=${APP_ADMIN_PASSWORD}





