create table lesson_student (
        id bigint generated by default as identity,
        currency enum ('EUR','PLN','UAH','USD'),
        payment_status enum ('FREE','PAID','PARTIALLY_PAID','UNPAID'),
        price numeric(38,2),
        lesson_id bigint not null,
        student_id bigint not null,
        primary key (id)
    );

create table lessons (
        id bigint generated by default as identity,
        lesson_date date not null,
        start_time time(6) not null,
        topic varchar(200),
        primary key (id)
    );

create table payments (
        id bigint generated by default as identity,
        amount numeric(38,2) not null,
        created_at timestamp(6) not null,
        currency enum ('EUR','PLN','UAH','USD') not null,
        payment_date date not null,
        payment_method enum ('CARD','CASH','PAYPAL') not null,
        updated_at timestamp(6) not null,
        student_id bigint not null,
        primary key (id)
    );

create table student_balance (
        id bigint generated by default as identity,
        amount numeric(38,2),
        currency enum ('EUR','PLN','UAH','USD'),
        last_updated_at timestamp(6),
        student_id bigint not null,
        primary key (id)
    );

create table students (
        id bigint generated by default as identity,
        active boolean not null,
        age integer,
        country varchar(50),
        created_at timestamp(6) not null,
        currency enum ('EUR','PLN','UAH','USD') not null,
        first_name varchar(50) not null,
        global_goal varchar(500),
        knowledge_level varchar(50),
        last_name varchar(50),
        phone_number varchar(50),
        price_group numeric(38,2) not null,
        price_individual numeric(38,2) not null,
        updated_at timestamp(6) not null,
        primary key (id)
    );

alter table if exists student_balance
       drop constraint if exists UKk3xnntpbvsegstynahavvyilr;

alter table if exists student_balance
       add constraint UKk3xnntpbvsegstynahavvyilr unique (student_id, balance_currency);

alter table if exists lesson_student
       add constraint FKphxx8ea2qix53enjoxe4hr5w
       foreign key (lesson_id)
       references lessons;

alter table if exists lesson_student
       add constraint FKi03u7ca29601ht8ft9vvu4ll3
       foreign key (student_id)
       references students;

alter table if exists payments
       add constraint FK6ooq278k2bs5xi8t5o6oort1v
       foreign key (student_id)
       references students;

alter table if exists student_balance
       add constraint FK9hfi3lt4rg41qtgo7di2mewni
       foreign key (student_id)
       references students;


